name: biobb_wf_virtual-screening
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_io==5.2.1
  - biobb_structure_utils==5.2.0
  - biobb_vs==5.2.0
  - biobb_chemistry==5.2.0
  - jupyterlab=3.6
  - nodejs=16
  - ipywidgets=7
  - nglview